/*
 * coder/llm.c — tiny JSON + HTTP client for OpenAI-compatible /v1/chat/completions
 *
 * Strategy:
 *  - Request:  hand-build the JSON body into a growing buffer, write to tempfile,
 *              invoke `curl` via popen, read response JSON from its stdout.
 *  - Response: parse with a minimal recursive-descent JSON parser that exposes
 *              only what we need (object-field lookup, array iter, string value).
 *
 * We don't need a general-purpose JSON library — the response shape is fixed
 * and small, and the request shape is generated by us. ~400 LOC total.
 */
#include "llm.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <errno.h>

/* ============================================================
 * Growing string buffer
 * ============================================================ */
typedef struct {
    char *buf;
    size_t len;
    size_t cap;
} sbuf_t;

static void sb_init(sbuf_t *s) { s->buf = NULL; s->len = 0; s->cap = 0; }
static void sb_free(sbuf_t *s) { free(s->buf); s->buf = NULL; s->len = s->cap = 0; }

static void sb_reserve(sbuf_t *s, size_t extra) {
    if (s->len + extra + 1 <= s->cap) return;
    size_t nc = s->cap ? s->cap * 2 : 256;
    while (nc < s->len + extra + 1) nc *= 2;
    char *nb = realloc(s->buf, nc);
    if (!nb) { perror("realloc"); exit(1); }
    s->buf = nb;
    s->cap = nc;
}

static void sb_putc(sbuf_t *s, char c) {
    sb_reserve(s, 1);
    s->buf[s->len++] = c;
    s->buf[s->len] = '\0';
}

static void sb_puts(sbuf_t *s, const char *str) {
    if (!str) return;
    size_t n = strlen(str);
    sb_reserve(s, n);
    memcpy(s->buf + s->len, str, n);
    s->len += n;
    s->buf[s->len] = '\0';
}

static void sb_write(sbuf_t *s, const char *data, size_t n) {
    sb_reserve(s, n);
    memcpy(s->buf + s->len, data, n);
    s->len += n;
    s->buf[s->len] = '\0';
}

/* JSON-escape a C string and append as a quoted string. */
static void sb_json_str(sbuf_t *s, const char *str) {
    sb_putc(s, '"');
    if (!str) { sb_putc(s, '"'); return; }
    for (const unsigned char *p = (const unsigned char *)str; *p; p++) {
        unsigned char c = *p;
        switch (c) {
            case '"':  sb_puts(s, "\\\""); break;
            case '\\': sb_puts(s, "\\\\"); break;
            case '\b': sb_puts(s, "\\b"); break;
            case '\f': sb_puts(s, "\\f"); break;
            case '\n': sb_puts(s, "\\n"); break;
            case '\r': sb_puts(s, "\\r"); break;
            case '\t': sb_puts(s, "\\t"); break;
            default:
                if (c < 0x20) {
                    char u[8];
                    snprintf(u, sizeof u, "\\u%04x", c);
                    sb_puts(s, u);
                } else {
                    sb_putc(s, (char)c);
                }
        }
    }
    sb_putc(s, '"');
}

/* ============================================================
 * Minimal JSON parser
 * ============================================================
 * Supports: object, array, string, number, true/false/null.
 * Produces a DOM of jval_t nodes. Not optimized, not general.
 */
typedef enum { JV_NULL, JV_BOOL, JV_NUM, JV_STR, JV_ARR, JV_OBJ } jtype_t;

typedef struct jval {
    jtype_t type;
    union {
        int b;
        double n;
        char *s; /* owned */
        struct { struct jval **items; int count; } arr;
        struct {
            char **keys; /* owned */
            struct jval **vals;
            int count;
        } obj;
    } u;
} jval_t;

typedef struct { const char *s; size_t pos; size_t len; int err; } jparser_t;

static void jskip_ws(jparser_t *p) {
    while (p->pos < p->len) {
        char c = p->s[p->pos];
        if (c == ' ' || c == '\t' || c == '\n' || c == '\r') p->pos++;
        else break;
    }
}

static jval_t *jnew(jtype_t t) {
    jval_t *v = calloc(1, sizeof(jval_t));
    v->type = t;
    return v;
}

static void jfree(jval_t *v);

static void jfree(jval_t *v) {
    if (!v) return;
    switch (v->type) {
        case JV_STR: free(v->u.s); break;
        case JV_ARR:
            for (int i = 0; i < v->u.arr.count; i++) jfree(v->u.arr.items[i]);
            free(v->u.arr.items);
            break;
        case JV_OBJ:
            for (int i = 0; i < v->u.obj.count; i++) {
                free(v->u.obj.keys[i]);
                jfree(v->u.obj.vals[i]);
            }
            free(v->u.obj.keys);
            free(v->u.obj.vals);
            break;
        default: break;
    }
    free(v);
}

static jval_t *jparse_val(jparser_t *p);

static char *jparse_str_raw(jparser_t *p) {
    if (p->pos >= p->len || p->s[p->pos] != '"') { p->err = 1; return NULL; }
    p->pos++;
    sbuf_t out; sb_init(&out);
    while (p->pos < p->len) {
        char c = p->s[p->pos++];
        if (c == '"') { return out.buf ? out.buf : strdup(""); }
        if (c == '\\') {
            if (p->pos >= p->len) { p->err = 1; sb_free(&out); return NULL; }
            char e = p->s[p->pos++];
            switch (e) {
                case '"':  sb_putc(&out, '"'); break;
                case '\\': sb_putc(&out, '\\'); break;
                case '/':  sb_putc(&out, '/'); break;
                case 'b':  sb_putc(&out, '\b'); break;
                case 'f':  sb_putc(&out, '\f'); break;
                case 'n':  sb_putc(&out, '\n'); break;
                case 'r':  sb_putc(&out, '\r'); break;
                case 't':  sb_putc(&out, '\t'); break;
                case 'u': {
                    if (p->pos + 4 > p->len) { p->err = 1; sb_free(&out); return NULL; }
                    unsigned cp = 0;
                    for (int i = 0; i < 4; i++) {
                        char h = p->s[p->pos++];
                        cp <<= 4;
                        if (h >= '0' && h <= '9') cp |= h - '0';
                        else if (h >= 'a' && h <= 'f') cp |= h - 'a' + 10;
                        else if (h >= 'A' && h <= 'F') cp |= h - 'A' + 10;
                        else { p->err = 1; sb_free(&out); return NULL; }
                    }
                    /* Minimal UTF-8 encode (BMP only; good enough for our paths) */
                    if (cp < 0x80) sb_putc(&out, (char)cp);
                    else if (cp < 0x800) {
                        sb_putc(&out, (char)(0xC0 | (cp >> 6)));
                        sb_putc(&out, (char)(0x80 | (cp & 0x3F)));
                    } else {
                        sb_putc(&out, (char)(0xE0 | (cp >> 12)));
                        sb_putc(&out, (char)(0x80 | ((cp >> 6) & 0x3F)));
                        sb_putc(&out, (char)(0x80 | (cp & 0x3F)));
                    }
                    break;
                }
                default: p->err = 1; sb_free(&out); return NULL;
            }
        } else {
            sb_putc(&out, c);
        }
    }
    p->err = 1;
    sb_free(&out);
    return NULL;
}

static jval_t *jparse_str(jparser_t *p) {
    char *s = jparse_str_raw(p);
    if (!s) return NULL;
    jval_t *v = jnew(JV_STR);
    v->u.s = s;
    return v;
}

static jval_t *jparse_num(jparser_t *p) {
    size_t start = p->pos;
    if (p->s[p->pos] == '-') p->pos++;
    while (p->pos < p->len && (isdigit((unsigned char)p->s[p->pos]) ||
           p->s[p->pos] == '.' || p->s[p->pos] == 'e' || p->s[p->pos] == 'E' ||
           p->s[p->pos] == '+' || p->s[p->pos] == '-')) p->pos++;
    char tmp[64];
    size_t n = p->pos - start;
    if (n >= sizeof tmp) { p->err = 1; return NULL; }
    memcpy(tmp, p->s + start, n);
    tmp[n] = '\0';
    jval_t *v = jnew(JV_NUM);
    v->u.n = strtod(tmp, NULL);
    return v;
}

static jval_t *jparse_arr(jparser_t *p) {
    p->pos++; /* [ */
    jval_t *v = jnew(JV_ARR);
    jskip_ws(p);
    if (p->pos < p->len && p->s[p->pos] == ']') { p->pos++; return v; }
    while (p->pos < p->len) {
        jval_t *item = jparse_val(p);
        if (!item) { jfree(v); return NULL; }
        v->u.arr.items = realloc(v->u.arr.items, sizeof(jval_t*) * (v->u.arr.count + 1));
        v->u.arr.items[v->u.arr.count++] = item;
        jskip_ws(p);
        if (p->pos >= p->len) { p->err = 1; jfree(v); return NULL; }
        if (p->s[p->pos] == ',') { p->pos++; jskip_ws(p); continue; }
        if (p->s[p->pos] == ']') { p->pos++; return v; }
        p->err = 1; jfree(v); return NULL;
    }
    p->err = 1; jfree(v); return NULL;
}

static jval_t *jparse_obj(jparser_t *p) {
    p->pos++; /* { */
    jval_t *v = jnew(JV_OBJ);
    jskip_ws(p);
    if (p->pos < p->len && p->s[p->pos] == '}') { p->pos++; return v; }
    while (p->pos < p->len) {
        jskip_ws(p);
        char *key = jparse_str_raw(p);
        if (!key) { jfree(v); return NULL; }
        jskip_ws(p);
        if (p->pos >= p->len || p->s[p->pos] != ':') {
            p->err = 1; free(key); jfree(v); return NULL;
        }
        p->pos++;
        jval_t *val = jparse_val(p);
        if (!val) { free(key); jfree(v); return NULL; }
        v->u.obj.keys = realloc(v->u.obj.keys, sizeof(char*) * (v->u.obj.count + 1));
        v->u.obj.vals = realloc(v->u.obj.vals, sizeof(jval_t*) * (v->u.obj.count + 1));
        v->u.obj.keys[v->u.obj.count] = key;
        v->u.obj.vals[v->u.obj.count] = val;
        v->u.obj.count++;
        jskip_ws(p);
        if (p->pos >= p->len) { p->err = 1; jfree(v); return NULL; }
        if (p->s[p->pos] == ',') { p->pos++; continue; }
        if (p->s[p->pos] == '}') { p->pos++; return v; }
        p->err = 1; jfree(v); return NULL;
    }
    p->err = 1; jfree(v); return NULL;
}

static jval_t *jparse_val(jparser_t *p) {
    jskip_ws(p);
    if (p->pos >= p->len) { p->err = 1; return NULL; }
    char c = p->s[p->pos];
    if (c == '{') return jparse_obj(p);
    if (c == '[') return jparse_arr(p);
    if (c == '"') return jparse_str(p);
    if (c == '-' || isdigit((unsigned char)c)) return jparse_num(p);
    if (p->pos + 4 <= p->len && memcmp(p->s + p->pos, "true", 4) == 0) {
        p->pos += 4; jval_t *v = jnew(JV_BOOL); v->u.b = 1; return v;
    }
    if (p->pos + 5 <= p->len && memcmp(p->s + p->pos, "false", 5) == 0) {
        p->pos += 5; jval_t *v = jnew(JV_BOOL); v->u.b = 0; return v;
    }
    if (p->pos + 4 <= p->len && memcmp(p->s + p->pos, "null", 4) == 0) {
        p->pos += 4; return jnew(JV_NULL);
    }
    p->err = 1;
    return NULL;
}

static jval_t *jparse(const char *s, size_t len) {
    jparser_t p = { .s = s, .pos = 0, .len = len, .err = 0 };
    jval_t *v = jparse_val(&p);
    if (p.err) { jfree(v); return NULL; }
    return v;
}

/* Helpers: object field lookup, array indexing. */
static jval_t *jfield(jval_t *obj, const char *key) {
    if (!obj || obj->type != JV_OBJ) return NULL;
    for (int i = 0; i < obj->u.obj.count; i++) {
        if (strcmp(obj->u.obj.keys[i], key) == 0) return obj->u.obj.vals[i];
    }
    return NULL;
}

/* Re-serialize a parsed jval back to canonical JSON (used to preserve the
 * raw JSON string of tool-call arguments, which we want to forward verbatim
 * into the tool handler). */
static void jser(sbuf_t *out, jval_t *v) {
    if (!v) { sb_puts(out, "null"); return; }
    switch (v->type) {
        case JV_NULL: sb_puts(out, "null"); break;
        case JV_BOOL: sb_puts(out, v->u.b ? "true" : "false"); break;
        case JV_NUM: {
            char tmp[64];
            if (v->u.n == (double)(long long)v->u.n)
                snprintf(tmp, sizeof tmp, "%lld", (long long)v->u.n);
            else
                snprintf(tmp, sizeof tmp, "%g", v->u.n);
            sb_puts(out, tmp);
            break;
        }
        case JV_STR: sb_json_str(out, v->u.s); break;
        case JV_ARR:
            sb_putc(out, '[');
            for (int i = 0; i < v->u.arr.count; i++) {
                if (i) sb_putc(out, ',');
                jser(out, v->u.arr.items[i]);
            }
            sb_putc(out, ']');
            break;
        case JV_OBJ:
            sb_putc(out, '{');
            for (int i = 0; i < v->u.obj.count; i++) {
                if (i) sb_putc(out, ',');
                sb_json_str(out, v->u.obj.keys[i]);
                sb_putc(out, ':');
                jser(out, v->u.obj.vals[i]);
            }
            sb_putc(out, '}');
            break;
    }
}

/* ============================================================
 * Message free
 * ============================================================ */
void llm_message_free(llm_message_t *msg) {
    if (!msg) return;
    free(msg->content); msg->content = NULL;
    free(msg->tool_call_id); msg->tool_call_id = NULL;
    for (int i = 0; i < msg->num_tool_calls; i++) {
        free(msg->tool_calls[i].arguments_json);
        msg->tool_calls[i].arguments_json = NULL;
    }
    msg->num_tool_calls = 0;
}

/* ============================================================
 * Request body builder
 * ============================================================ */
static void build_request(sbuf_t *out,
                          const llm_client_t *c,
                          const llm_message_t *msgs, int num_msgs,
                          const llm_tool_def_t *tools, int num_tools) {
    sb_putc(out, '{');
    sb_puts(out, "\"model\":"); sb_json_str(out, c->model);
    sb_puts(out, ",\"temperature\":0.2");
    sb_puts(out, ",\"messages\":[");
    for (int i = 0; i < num_msgs; i++) {
        if (i) sb_putc(out, ',');
        const llm_message_t *m = &msgs[i];
        sb_putc(out, '{');

        /* Many simple servers (e.g. transformers serve) choke on OpenAI's
         * "tool" role and on assistant messages with a structured tool_calls
         * field. Flatten everything to user/assistant/system with plain text:
         *   - role="tool"  → role="user", content wrapped in <tool_result>
         *   - assistant with tool_calls → re-embed calls as inline
         *     <tool_call>{...}</tool_call> blocks in content.
         */
        const char *role = m->role;
        int is_tool_role = strcmp(role, "tool") == 0;
        if (is_tool_role) role = "user";

        sb_puts(out, "\"role\":"); sb_json_str(out, role);
        sb_puts(out, ",\"content\":");

        /* Build the effective content string. */
        sbuf_t c; sb_init(&c);
        if (is_tool_role) {
            sb_puts(&c, "<tool_result>\n");
            if (m->content) sb_puts(&c, m->content);
            sb_puts(&c, "\n</tool_result>");
        } else {
            if (m->content) sb_puts(&c, m->content);
            if (strcmp(role, "assistant") == 0 && m->num_tool_calls > 0) {
                for (int k = 0; k < m->num_tool_calls; k++) {
                    if (c.len > 0) sb_putc(&c, '\n');
                    sb_puts(&c, "<tool_call>{\"name\":\"");
                    sb_puts(&c, m->tool_calls[k].name);
                    sb_puts(&c, "\",\"arguments\":");
                    sb_puts(&c, m->tool_calls[k].arguments_json
                                    ? m->tool_calls[k].arguments_json : "{}");
                    sb_puts(&c, "}</tool_call>");
                }
            }
        }

        sb_json_str(out, c.buf ? c.buf : "");
        sb_free(&c);
        sb_putc(out, '}');
    }
    sb_putc(out, ']');

    if (num_tools > 0) {
        sb_puts(out, ",\"tools\":[");
        for (int i = 0; i < num_tools; i++) {
            if (i) sb_putc(out, ',');
            sb_puts(out, "{\"type\":\"function\",\"function\":{");
            sb_puts(out, "\"name\":"); sb_json_str(out, tools[i].name);
            sb_puts(out, ",\"description\":"); sb_json_str(out, tools[i].description);
            sb_puts(out, ",\"parameters\":");
            sb_puts(out, tools[i].params_schema_json);
            sb_puts(out, "}}");
        }
        sb_putc(out, ']');
        sb_puts(out, ",\"tool_choice\":\"auto\"");
    }
    sb_putc(out, '}');
}

/* ============================================================
 * HTTP via curl subprocess
 * ============================================================ */
static int http_post_json(const llm_client_t *c, const char *body, sbuf_t *resp) {
    /* Write body to a temp file so curl can POST it without shell-escaping hell. */
    char req_path[] = "/tmp/coder_req_XXXXXX";
    int fd = mkstemp(req_path);
    if (fd < 0) { perror("mkstemp"); return -1; }
    FILE *fp = fdopen(fd, "w");
    if (!fp) { close(fd); unlink(req_path); return -1; }
    fwrite(body, 1, strlen(body), fp);
    fclose(fp);

    /* Build curl command. */
    sbuf_t cmd; sb_init(&cmd);
    sb_puts(&cmd, "curl -sS --max-time 600 -X POST ");
    sb_putc(&cmd, '\'');
    sb_puts(&cmd, c->endpoint);
    sb_puts(&cmd, "/v1/chat/completions");
    sb_putc(&cmd, '\'');
    sb_puts(&cmd, " -H 'Content-Type: application/json'");
    if (c->api_key && *c->api_key) {
        sb_puts(&cmd, " -H 'Authorization: Bearer ");
        sb_puts(&cmd, c->api_key);
        sb_putc(&cmd, '\'');
    }
    sb_puts(&cmd, " --data-binary @");
    sb_puts(&cmd, req_path);

    if (c->verbose) fprintf(stderr, "[llm] POST %s/v1/chat/completions\n", c->endpoint);

    FILE *pp = popen(cmd.buf, "r");
    sb_free(&cmd);
    if (!pp) { unlink(req_path); return -1; }
    char chunk[4096];
    size_t r;
    while ((r = fread(chunk, 1, sizeof chunk, pp)) > 0) {
        sb_write(resp, chunk, r);
    }
    int rc = pclose(pp);
    unlink(req_path);
    if (rc != 0) {
        fprintf(stderr, "[llm] curl exited with rc=%d\n", rc);
        return -1;
    }
    return 0;
}

/* ============================================================
 * Response parse
 * ============================================================ */
static int parse_response(const char *resp, size_t len, llm_message_t *out) {
    jval_t *root = jparse(resp, len);
    if (!root) {
        fprintf(stderr, "[llm] failed to parse response JSON\n");
        return -1;
    }

    /* Surface API errors. */
    jval_t *err = jfield(root, "error");
    if (err) {
        jval_t *emsg = jfield(err, "message");
        fprintf(stderr, "[llm] API error: %s\n",
                (emsg && emsg->type == JV_STR) ? emsg->u.s : "(unknown)");
        jfree(root);
        return -1;
    }

    jval_t *choices = jfield(root, "choices");
    if (!choices || choices->type != JV_ARR || choices->u.arr.count == 0) {
        fprintf(stderr, "[llm] no choices in response\n");
        jfree(root);
        return -1;
    }
    jval_t *choice0 = choices->u.arr.items[0];
    jval_t *msg = jfield(choice0, "message");
    if (!msg) {
        fprintf(stderr, "[llm] no message in choice\n");
        jfree(root);
        return -1;
    }

    strcpy(out->role, "assistant");

    jval_t *content = jfield(msg, "content");
    if (content && content->type == JV_STR && content->u.s[0] != '\0') {
        out->content = strdup(content->u.s);
    }

    jval_t *tcs = jfield(msg, "tool_calls");
    if (tcs && tcs->type == JV_ARR) {
        int n = tcs->u.arr.count;
        if (n > LLM_MAX_TOOL_CALLS) n = LLM_MAX_TOOL_CALLS;
        out->num_tool_calls = n;
        for (int i = 0; i < n; i++) {
            jval_t *tc = tcs->u.arr.items[i];
            jval_t *id = jfield(tc, "id");
            jval_t *fn = jfield(tc, "function");
            if (id && id->type == JV_STR) {
                strncpy(out->tool_calls[i].id, id->u.s, sizeof out->tool_calls[i].id - 1);
            } else {
                snprintf(out->tool_calls[i].id, sizeof out->tool_calls[i].id, "call_%d", i);
            }
            if (fn) {
                jval_t *fname = jfield(fn, "name");
                jval_t *fargs = jfield(fn, "arguments");
                if (fname && fname->type == JV_STR) {
                    strncpy(out->tool_calls[i].name, fname->u.s,
                            sizeof out->tool_calls[i].name - 1);
                }
                /* arguments may be either a JSON string or an object. Normalize
                 * to a JSON-string representation we can pass to the tool. */
                if (fargs) {
                    if (fargs->type == JV_STR) {
                        out->tool_calls[i].arguments_json = strdup(fargs->u.s);
                    } else {
                        sbuf_t s; sb_init(&s);
                        jser(&s, fargs);
                        out->tool_calls[i].arguments_json = s.buf ? s.buf : strdup("{}");
                    }
                }
            }
        }
    }

    jfree(root);
    return 0;
}

/* ============================================================
 * Public entry
 * ============================================================ */
int llm_chat(const llm_client_t *c,
             const llm_message_t *msgs, int num_msgs,
             const llm_tool_def_t *tools, int num_tools,
             llm_message_t *out_assistant) {
    if (!c || !msgs || !out_assistant) return -1;
    memset(out_assistant, 0, sizeof *out_assistant);

    sbuf_t body; sb_init(&body);
    build_request(&body, c, msgs, num_msgs, tools, num_tools);

    if (c->verbose) {
        fprintf(stderr, "[llm] request body (%zu bytes):\n%s\n", body.len, body.buf);
    }

    sbuf_t resp; sb_init(&resp);
    int rc = http_post_json(c, body.buf, &resp);
    sb_free(&body);
    if (rc != 0) {
        if (resp.buf) fprintf(stderr, "[llm] response so far: %s\n", resp.buf);
        sb_free(&resp);
        return -1;
    }

    if (c->verbose) {
        fprintf(stderr, "[llm] response (%zu bytes):\n%s\n", resp.len, resp.buf);
    }

    rc = parse_response(resp.buf ? resp.buf : "", resp.len, out_assistant);
    sb_free(&resp);
    return rc;
}
